DEI-148: Deploy to PROD
tetrascience/ts-data-insights-ci-cd-common pull request #37
Opened 2022-08-08 13:29 UTC by VladimirShteyn

## JIRA ticket

https://tetrascience.atlassian.net/browse/DEI-148

## Description

Calls the Github Action which deploys to PROD.

## Supporting test data

Testing done manually by deploying to PROD. See the following links to the PROD S3 buckets:

[ts-client-diagnostic-dei-regression-task-script](https://s3.console.aws.amazon.com/s3/buckets/ts-platform-artifacts-us-east-1?region=us-east-1&prefix=clients/ts-platform/protocol-scripts/production/task-scripts/client-diagnostic/dei-regression/v1.1.0/&showversions=false)
[ts-client-diagnostic-dei-regression-protocol](https://s3.console.aws.amazon.com/s3/buckets/ts-platform-artifacts-us-east-1?region=us-east-1&prefix=clients/ts-platform/protocol-scripts/production/master-scripts/client-diagnostic/dei-regression/v0.1.0/&showversions=false)
[ts-client-diagnostic-dei-regression-ids](https://s3.console.aws.amazon.com/s3/buckets/ts-platform-artifacts-us-east-1?region=us-east-1&prefix=clients/ts-platform/protocol-scripts/production/ids/client-diagnostic/dei-regression/v0.1.0/&showversions=false)

2022-08-08 19:24 UTC, abclay requested changes

2022-08-08 19:24 UTC, abclay commented on .github/workflows/publish.yml
> +        uses: tetrascience/ts-deploy-task-script-action@main
Once the deploy action is merged and tested, let's tag it and point at that.  ci-cd-common should always point to tagged versions of actions so we don't accidentally roll out code to all repos.

2022-08-08 19:24 UTC, abclay commented on .github/workflows/publish_tag.yml
> +          INPUT_ARTIFACT_TYPE: ${{ inputs.type }}
We could also just completely skip this step if the input type is not 'task-script':

```suggestion
      - name: "Setup Python Dependency Manager"
        if: ${{ inputs.type === 'task-script }}
        shell: bash
```

(disclaimer: I have not tested this, but I think it would work)

2022-08-08 19:24 UTC, abclay commented on .github/workflows/publish_tag.yml
> +        uses: tetrascience/ts-deploy-task-script-action@main
Another place to pin the action.

2022-08-08 19:24 UTC, abclay commented on .github/workflows/publish_tag.yml
> +      - name: "Display Artifact URL"
🏆

2022-08-08 19:24 UTC, abclay commented on .github/workflows/publish_tag.yml
> +    needs: [determine-tag-and-ref, validate-tag]
Should we also wait for `publish-dev-uat` ?  I would think we should make sure that worked before letting this one go.

2022-08-08 19:24 UTC, abclay commented on .github/workflows/publish_tag.yml
> +    environment: DEV/UAT
```suggestion
    environment: PRODUCTION
```

2022-08-08 19:24 UTC, abclay commented on .github/workflows/run_artifact_tests.yml
> +name: Run tests for artifact:tag
Where is this called?  Is it part of the publish process?

2022-08-12 12:49 UTC, VladimirShteyn commented on .github/workflows/publish_tag.yml
> +    needs: [determine-tag-and-ref, validate-tag]
In that case, if the `deploy-to-dev-uat` input is set to `false` and `deploy-to-prod` input is set to `true`, the `deploy-to-prod` will never run. I can see a use case for only deploying to PROD if the user knows that same version has already been deployed to DEV/UAT.

2022-08-12 12:50 UTC, VladimirShteyn commented on .github/workflows/publish_tag.yml
> +    environment: DEV/UAT
Good catch.

2022-08-12 12:50 UTC, VladimirShteyn commented on .github/workflows/run_artifact_tests.yml
> +name: Run tests for artifact:tag
This file can be deleted.

2022-08-12 13:21 UTC, VladimirShteyn commented on .github/workflows/publish.yml
> +        uses: tetrascience/ts-deploy-task-script-action@main
OK I'll change `main` -> `v0.6.0`.

2022-08-12 13:21 UTC, VladimirShteyn commented on .github/workflows/publish_tag.yml
> +        uses: tetrascience/ts-deploy-task-script-action@main
OK I'll change `main` -> `v0.6.0`.

2022-08-12 13:29 UTC, VladimirShteyn commented on .github/workflows/publish_tag.yml
> +          INPUT_ARTIFACT_TYPE: ${{ inputs.type }}
Can we do this optimization in another ticket? Ideally we'd implement some Python dependency caching too and put the `if` statement in the above "Setup Python" step.

2022-08-12 14:07 UTC, apjansing approved these changes
Looks good to me.
The only thing I'm thinking we could do to improve this would be is use aliases and anchors so you can just update things like `tetrascience/ts-deploy-task-script-action@v0.6.0` in one spot and have it update everywhere else in the yaml

https://www.linode.com/docs/guides/yaml-anchors-aliases-overrides-extensions/

2022-08-12 14:44 UTC, mlipschultz commented on .github/workflows/publish_tag.yml
> +          INPUT_ARTIFACT_TYPE: ${{ inputs.type }}
I think we'd want to also set up the python environment for IDS repos (in case they're P-IDS). So as long as this doesn't cause problems for non-Python artifacts, I'm fine keeping things the way they are for now (i.e. I agree with Vlad).

2022-08-12 14:44 UTC, mlipschultz commented on .github/workflows/publish_tag.yml
> +    needs: [determine-tag-and-ref, validate-tag]
Is there a reason you'd have that configuration though?  The flow from DI is you deploy to dev/UAT, test, then only if it passes do you release to production.  I don't think we need to support a flow that shouldn't be used.

2022-08-12 16:09 UTC, VladimirShteyn commented on .github/workflows/publish_tag.yml
> +    needs: [determine-tag-and-ref, validate-tag]
What if the user knows that `v1.2.3` is already deployed on DEV/UAT? Users would be much happier if they didn't have to wait for `v1.2.3` to get build and deployed to DEV/UAT all over again. Ideally deploying to PROD would be gated not only on manual approval but also checking whether TDP contains the same artifact in DEV/UAT. It's not worth doing right now but perhaps worth considering once AMS is implemented. In any case, it seems like we always want to deploy to DEV/UAT. Should we just remove the `input.deploy-to-dev-uat`? In that case I'd be happy to have PROD require first deploy to DEV/UAT.

2022-08-12 16:12 UTC, VladimirShteyn commented on .github/workflows/publish_tag.yml
> +        default: true
Correct, there's nothing stopping them. Should I change it back to `false`?

2022-08-12 16:13 UTC, VladimirShteyn commented on .github/workflows/publish_tag.yml
> +      - name: "Display Artifact URL"
😸

2022-08-12 16:16 UTC, VladimirShteyn commented
> Looks good to me. The only thing I'm thinking we could do to improve this would be is use aliases and anchors so you can just update things like `tetrascience/ts-deploy-task-script-action@v0.6.0` in one spot and have it update everywhere else in the yaml
> 
> https://www.linode.com/docs/guides/yaml-anchors-aliases-overrides-extensions/

That is a great idea!

2022-08-12 16:23 UTC, mlipschultz commented on .github/workflows/publish_tag.yml
> +        default: true
Yes, please change it back.

2022-08-12 16:37 UTC, mlipschultz commented on .github/workflows/publish_tag.yml
> +    needs: [determine-tag-and-ref, validate-tag]
> What if the user knows that v1.2.3 is already deployed on DEV/UAT?

Then either:
1. There's a release build in progress that put v1.2.3 in dev/uat and it's now waiting for someone to approve so it can deploy to production
2. There was a release build in progress that put v1.2.3 in dev/uat, but it needed to be aborted and v1.2.3 should not go to production.  For example: During testing in UAT it was discovered that v1.2.3 had a bug.  The bug was fixed and now it's time to release again.  That new release should still go through dev/uat for another round of testing and so that the artifacts in dev/uat match what's in production.

Is there another case I'm missing?  If not, then I don't think there's an actual use case we need to support.

> Should we just remove the input.deploy-to-dev-uat since every pipeline should deploy to DEV/UAT?
Perhaps, but because we have so much in progress right now and it'll touch a bunch of repos (and therefore probably a few existing PRs), I'd rather handle that in a separate ticket.

2022-08-12 18:07 UTC, VladimirShteyn commented on .github/workflows/publish_tag.yml
> +        default: true
Done.

2022-08-12 18:07 UTC, VladimirShteyn commented on .github/workflows/publish_tag.yml
> +    needs: [determine-tag-and-ref, validate-tag]
Ok, the workflow is now linear.

2022-08-15 08:55 UTC, setiat approved these changes
All good! Just a minor request to update the acceptance criterion for DEI-80.

2022-08-15 08:55 UTC, setiat commented on .github/workflows/publish_tag.yml
> +  publish-prod:
Creating this Job, is a part of DEI-80.
Acceptance criterion of DEI-80 should be updated.

2022-08-15 17:24 UTC, merged