DEI-185: Enable pulling from Artifactory
tetrascience/ts-data-insights-ci-cd-common pull request #49
Opened 2022-08-18 14:27 UTC by VladimirShteyn

## JIRA ticket

## Description

## Supporting test data

## Automated testing

- [ ] Unit tests
- [ ] Integration tests
- [ ] API tests
- [ ] End-To-End tests
- [ ] N/A (please clarify)

2022-08-18 16:27 UTC, aslotte commented on .github/workflows/publish_tag.yml
> +      require-private-pypi:
I would remove this input, I think that can be inferred from the JFrog Artifactory secrets instead

2022-08-18 16:28 UTC, aslotte commented on .github/workflows/publish.yml
> +          poetry config repositories.ts_pypi_virtual ${{ secrets.JFROG_ARTIFACTORY_URL }}
We need to have the same conditional logic here

2022-08-18 16:28 UTC, aslotte commented
Awesome @VladimirShteyn! Left two comments

2022-08-18 19:01 UTC, VladimirShteyn commented on .github/workflows/publish.yml
> +          poetry config repositories.ts_pypi_virtual ${{ secrets.JFROG_ARTIFACTORY_URL }}
Fixed.

2022-08-18 19:01 UTC, VladimirShteyn commented on .github/workflows/publish_tag.yml
> +      require-private-pypi:
Removed.

2022-08-18 19:04 UTC, aslotte commented on .github/workflows/publish.yml
> +          if [[ ${{ secrets.JFROG_ARTIFACTORY_URL }} && ${{ secrets.JFROG_ARTIFACTORY_USER }} && ${{ secrets.JFROG_ARTIFACTORY_PASSWORD }} }} ]]; then
Looks to be an extra `}}` at the end, but I may be mistaken :)

2022-08-18 19:05 UTC, aslotte commented on .github/workflows/publish_tag.yml
> +        uses: tetrascience/ts-deploy-task-script-action@DEI-185
Figured this is for testing the action, just a reminder to change it after merge and new version of the action 👍

2022-08-19 20:33 UTC, aslotte commented on .github/workflows/publish.yml
> +          sudo apt-get update
I think we should change this to `pip install envsubst` as it's not descriptive enough of what package we are using

2022-08-19 20:33 UTC, aslotte commented on .github/workflows/publish.yml
> +          sudo apt-get update
It's also only needed for `pipenv` so I would just move this into the conditional logic for `pipenv`

2022-08-19 21:54 UTC, VladimirShteyn commented on .github/workflows/publish.yml
> +          sudo apt-get update
The `apt-get` seems like a more official source though. Maybe I can add a log statement explaining that this installs `envsubst`?

2022-08-19 21:55 UTC, VladimirShteyn commented on .github/workflows/publish_tag.yml
> +        uses: tetrascience/ts-deploy-task-script-action@DEI-185
Will do.

 - [ ] Update `ts-deploy-task-script-action` ref

2022-08-19 22:00 UTC, VladimirShteyn commented on .github/workflows/publish.yml
> +          if [[ ${{ secrets.JFROG_ARTIFACTORY_URL }} && ${{ secrets.JFROG_ARTIFACTORY_USER }} && ${{ secrets.JFROG_ARTIFACTORY_PASSWORD }} }} ]]; then
Thanks. Fixed.

2022-08-22 13:26 UTC, aslotte commented on .github/workflows/publish.yml
> +          sudo apt-get update
Feel free to loop someone else in on this, a third-opinion is probably good, but I feel pretty strongly about this

2022-08-22 13:41 UTC, abclay commented on .github/workflows/publish.yml
> +          sudo apt-get update
Is `envsubst` from `pip` the same as the utility in `gettext`?  It doesn't look like it to me.

2022-08-22 17:25 UTC, apjansing reviewed
Looks good, other than the `tetrascience/ts-deploy-task-script-action@DEI-185` but that was pointed around already

2022-08-22 18:09 UTC, aslotte commented on .github/workflows/publish.yml
> +          sudo apt-get update
I'm not sure, but `pip install envsubst` is more clear to me

2022-08-22 18:27 UTC, abclay commented on .github/workflows/publish.yml
> +          sudo apt-get update
I experimented a bit.  It looks like installing `envsubst` using python/pip will provide a CLI tool with the same name that does what we want.  `envsubst` is also defined as part of the GNU `gettext` package ([docs](https://www.gnu.org/software/gettext/manual/html_node/envsubst-Invocation.html)).  This is a more fully-featured CLI tool, with options and a `man` page.  

The python version is from this repo: https://github.com/ashafer01/python-envsubst

If we're going to use a version of this functionality that someone random has written and put up on github, I would prefer that the action uses a node module instead of doing a syscall to a separate CLI app.  I noted this in a comment on the action repo: https://github.com/tetrascience/ts-deploy-task-script-action/pull/30#discussion_r951413386

2022-08-22 21:42 UTC, abclay requested changes

2022-08-22 21:42 UTC, abclay commented on .github/workflows/publish.yml
> +          sudo apt-get update
With the latest changes, this "Install envsubst" step should be removed from both the dev/uat and prod jobs.

2022-08-23 14:27 UTC, VladimirShteyn commented on .github/workflows/publish.yml
> +          sudo apt-get update
Done.

2022-08-23 15:42 UTC, aslotte commented on .github/workflows/publish.yml
> +          JFROG_ARTIFACTORY_URL="${{ secrets.JFROG_ARTIFACTORY_URL }}"
For consistency, let's move these to env variables for the specific step instead. Same across the workflows

2022-08-23 15:42 UTC, aslotte commented on .github/workflows/publish.yml
> +        shell: bash
No need to set `shell: bash` across the files. The default shell in a GitHub Action ubuntu runner is bash already

2022-08-23 16:16 UTC, VladimirShteyn commented on .github/workflows/publish.yml
> +        shell: bash
Fixed.

2022-08-23 16:16 UTC, VladimirShteyn commented on .github/workflows/publish.yml
> +          JFROG_ARTIFACTORY_URL="${{ secrets.JFROG_ARTIFACTORY_URL }}"
Fixed.

2022-08-23 16:17 UTC, aslotte commented on .github/workflows/publish_tag.yml
> +          echo "Installing the shell command, 'envsubst'"
Not needed anymore

2022-08-23 16:23 UTC, aslotte approved these changes
Nice work @VladimirShteyn! ⭐

2022-08-23 16:27 UTC, abclay approved these changes
⭐ ⭐ ⭐ ⭐ ⭐

2022-08-23 16:28 UTC, merged