DEI-292: Enable GitHub PAT
tetrascience/ts-data-insights-ci-cd-common pull request #78
Opened 2022-10-27 20:08 UTC by VladimirShteyn

## JIRA ticket

https://tetrascience.atlassian.net/browse/DEI-292

## Description

This is required to run the `ts-version-folders-to-git` integration tests, which call the GitHub API, e.g. [this one](https://github.com/tetrascience/ts-version-folders-to-git/blob/DEI-292-publish-ids-artifacts/tests/publish_ids_artifacts/test_github_api.py#L56-L68). 

## Supporting test data

## Automated testing

- [ ] Unit tests
- [ ] Integration tests
- [ ] API tests
- [ ] End-To-End tests
- [ ] N/A (please clarify)

2022-10-28 11:33 UTC, mlipschultz commented on .github/workflows/python_code_quality.yml
> +          GITHUB_USER: ${{ secrets.GITHUB_USER }}
How does this affect all of the repos using this workflow that won't have these secrets?

2022-10-28 13:50 UTC, VladimirShteyn commented on .github/workflows/python_code_quality.yml
> +          GITHUB_USER: ${{ secrets.GITHUB_USER }}
The `GITHUB_USER` and `GITHUB_TOKEN` secrets are optional, so it shouldn't affect other repos.

2022-10-28 15:39 UTC, mlipschultz requested changes
Based on a quick test, it looks like this change will break all repositories using `python_code_quality.yml` and not providing `GITHUB_USER` and `GITHUB_TOKEN`

2022-10-28 15:39 UTC, mlipschultz commented on .github/workflows/python_code_quality.yml
> +          GITHUB_USER: ${{ secrets.GITHUB_USER }}
That doesn't appear to be the case.

This PR uses this branch's changes: https://github.com/tetrascience/ts-client-diagnostic-task-script-dei-regression/pull/22  You'll see that it's stuck on the two python code quality checks.

However, this PR where we use `main` isn't stuck on those checks: https://github.com/tetrascience/ts-client-diagnostic-task-script-dei-regression/pull/23

2022-10-28 17:17 UTC, VladimirShteyn commented on .github/workflows/python_code_quality.yml
> +          GITHUB_USER: ${{ secrets.GITHUB_USER }}
Thanks for creating the test PRs. I've changed their titles to reflect their association with this ticket -- and so Conventions Bot gives the PR a ✅. 🤖 The successful build is [here](https://github.com/tetrascience/ts-client-diagnostic-task-script-dei-regression/actions/runs/3346638234/jobs/5543692151).

As a second test, the PR has also been updated such that it uses `poetry` instead of `pipenv`. [Here](https://github.com/tetrascience/ts-client-diagnostic-task-script-dei-regression/actions/runs/3347239112/jobs/5545008163) is the `poetry` test.

2022-10-31 14:21 UTC, mlipschultz approved these changes

2022-10-31 14:21 UTC, merged