DEI-423: Add dotnet build steps to publish_tag.yml
tetrascience/ts-data-insights-ci-cd-common pull request #82
Opened 2022-11-29 20:10 UTC by nilsguillermin

## JIRA ticket

https://tetrascience.atlassian.net/browse/DEI-423

## Description

This PR adds the dotnet (core and framework) build steps to the publish_tag.yml workflow.

## Supporting test data

## Automated testing

- [ ] Unit tests
- [ ] Integration tests
- [ ] API tests
- [ ] End-To-End tests
- [ ] N/A (please clarify)

2022-12-01 13:49 UTC, mlipschultz requested changes
I have a few suggestions on name changes and a potential correction to the flow if there's a `bin` directory.  I'm not familiar enough with compiling C# or with github actions to know if the build steps actually work correctly, but I guess that's what your tests are for

2022-12-01 13:49 UTC, mlipschultz commented on .github/workflows/publish_tag.yml
> +          if [[ -d "dotnetcore" && ! -L "dotnetcore" ]]; then
In case you're like me and don't have your bash conditionals memorized, I found [this page](https://www.gnu.org/software/bash/manual/html_node/Bash-Conditional-Expressions.html) to help me interpret:
* `-d` = Does the file exist and is it a directory?
* `-L` = Does the file exist and is it a symbolic link?

2022-12-01 13:49 UTC, mlipschultz commented on .github/workflows/publish_tag.yml
> +            echo "dotnetversion=framework" >> $GITHUB_OUTPUT
Any reason for choosing `framework` over `dotnetframework`?  I'm asking because the checks above are for `dotnetframework` and above that everything's `dotnetcore`, so I'd expect `dotnet` at the start of `framework`

2022-12-01 13:49 UTC, mlipschultz commented on .github/workflows/publish_tag.yml
> +  build-dotnet:
This name made me think it's for both kinds of dotnet, but it looks like it's just for dotnetcore.  Perhaps rename it to `build-core` or `build-dotnetcore`.

2022-12-01 13:49 UTC, mlipschultz commented on .github/workflows/publish_tag.yml
> +        run: mkdir bin
This will fail if there's already a `bin` directory, I think this will fail.  It's possible this directory already exists and if it does, [we're supposed to just use what's already there](https://tetrascience.atlassian.net/wiki/spaces/DE/pages/3482877960/Include+.NET+Source+Code+inside+Task+Script#Decision-%233%3A-Build-Process)

2022-12-01 13:49 UTC, mlipschultz commented on .github/workflows/publish_tag.yml
> +      - name: Find Solution Name
I think we only want to do these steps if there's no top-level `bin` directory.  If there is, then [we're supposed to just use what's already there](https://tetrascience.atlassian.net/wiki/spaces/DE/pages/3482877960/Include+.NET+Source+Code+inside+Task+Script#Decision-%233%3A-Build-Process)

2022-12-01 15:27 UTC, nilsguillermin commented on .github/workflows/publish_tag.yml
> +      - name: Find Solution Name
Good catch! Will add this functionality.

2022-12-01 15:27 UTC, nilsguillermin commented on .github/workflows/publish_tag.yml
> +        run: mkdir bin
Good catch! Will add this functionality.

2022-12-01 15:28 UTC, nilsguillermin commented on .github/workflows/publish_tag.yml
> +          if [[ -d "dotnetcore" && ! -L "dotnetcore" ]]; then
Just going to ignore the PowerShell entirely 😆 ?

2022-12-01 16:10 UTC, nilsguillermin commented on .github/workflows/publish_tag.yml
> +            echo "dotnetversion=framework" >> $GITHUB_OUTPUT
Done.

2022-12-01 16:49 UTC, mlipschultz commented on .github/workflows/publish_tag.yml
> +          if [[ -d "dotnetcore" && ! -L "dotnetcore" ]]; then
No, I just forget it even exists :)

2022-12-01 18:27 UTC, nilsguillermin commented on .github/workflows/publish_tag.yml
> +          if [[ -d "dotnetcore" && ! -L "dotnetcore" ]]; then
Wish I could do the same right now :(

2022-12-01 18:27 UTC, nilsguillermin commented on .github/workflows/publish_tag.yml
> +        run: mkdir bin
Will also add these changes to publish.yml

2022-12-01 18:28 UTC, nilsguillermin commented on .github/workflows/publish_tag.yml
> +      - name: Find Solution Name
Will also add these changes to publish.yml

2022-12-01 18:36 UTC, mlipschultz approved these changes
Changes look good to me

2022-12-06 14:40 UTC, apjansing approved these changes
Looks good to me. The only thing that popped out to me, is that I wonder how the `publish.yml` workflow handles its Python path with and without dotnet code

2022-12-07 11:44 UTC, merged