DEI-514: Naively copy e2e tests section to publish.yml
tetrascience/ts-data-insights-ci-cd-common pull request #90
Opened 2023-01-19 17:05 UTC by nilsguillermin

## JIRA ticket

https://tetrascience.atlassian.net/browse/DEI-514

## Description

Implement running E2E tests at PR-time.

## Supporting test data

## Automated testing

- [ ] Unit tests
- [ ] Integration tests
- [ ] API tests
- [ ] End-To-End tests
- [ ] N/A (please clarify)

2023-01-25 14:42 UTC, mlipschultz commented
> Timeout exceeded test was performed by removing update line in while loop.
https://github.com/tetrascience/ts-protocol-test-nils-dei-514/actions/runs/4005006748/jobs/6874848222

Thanks for doing that test!  Is 20 minutes sufficient in the cases you saw?  Is 20 minutes configurable?

It looks like waiting is billable time in this case: https://github.com/tetrascience/ts-protocol-test-nils-dei-514/actions/runs/4005006748/usage  I wonder if there's a way to reduce it.  Maybe we can include Alex Slotte in this conversation to either figure out how to reduce it or get an idea if it'll create a problem.  Any idea how long a typical run is?

2023-01-25 14:58 UTC, mlipschultz requested changes
Overall, the implementation looks ok.  I do have a question about the if check on the version number, but maybe I'm not familiar enough with bash regex behavior.

2023-01-25 14:58 UTC, mlipschultz commented on .github/workflows/publish.yml
> +            ARTIFACT_TYPE="task-scripts"
Given the if block above (namely `inputs.type == 'protocol'`), won't this always be false?

2023-01-25 14:58 UTC, mlipschultz commented on .github/workflows/publish.yml
> +          if [[ $VERSION =~ ^v[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
Shouldn't the fourth `\.[0-9]+` be optional since not all tags with include a build number (I assume based on the line from the `determine-tag` step: `"v0.0.${{ github.event.number }}"`)

2023-01-25 15:08 UTC, nilsguillermin commented on .github/workflows/publish.yml
> +            ARTIFACT_TYPE="task-scripts"
Sounds about right.

2023-01-25 15:28 UTC, nilsguillermin commented on .github/workflows/publish.yml
> +          if [[ $VERSION =~ ^v[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
After reviewing this code, I believe it is completely irrelevant, since we are the ones generating the version number earlier in `determine-tag` job. Removed this step in the job.

2023-02-01 12:38 UTC, mlipschultz approved these changes
The busy-wait implementation that goes through codebuild is good enough for now.  We'll tackling improving that in other PRs.

2023-02-01 14:02 UTC, merged